### ISSUE TITLE
Cant get plug to work with Phoenix

### ISSUE THREAD

**Issue by AdamBrodzinski** [bryanjos/joken#141]
I'm fairly new to JWT and plug and i'm having a hard time getting Phoenix to run the plug. I've tried using the example verbatim but there seems to be a discrepancy with Plug router and Phoenix router. 

```text
== Compilation error on file lib/api/router.ex ==
** (CompileError) lib/api/router.ex:4: undefined function match/2
    (stdlib) lists.erl:1337: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8
```

Using this in my router:

```elixir
defmodule Api.Router do
  use Api.Web, :router
  @jwt_secret Application.get_env(:api, :jwt_secret)

  pipeline :api do
    plug Joken.Plug, verify: &Api.Router.verify_function/0
    plug :match    # ** runs but doesnt work if this is commented out **
    plug :dispatch
    plug :accepts, ["json"]
  end

  scope "/api" do
    post "/", Absinthe.Plug, schema: Api.PublicSchema
  end

  def verify_function() do
    IO.puts "running verify"

    %Joken.Token{}
    |> Joken.with_signer(Joken.hs256(@jwt_secret))
    |> Joken.with_sub(1234567890)
  end
end
```

If I comment out `plug :match` then it will compile and run but no the Joken plug is not run.

Any help on debugging this would be greatly appreciated! I'd be happy to PR a phoenix section in the readme if we can get this going 👍

**Comment by AdamBrodzinski** [comment]
Got it... stupid mistake 😆  I forget to add `pipe_through :api` to my scope block.

Keep up the good work 🍻
